# Generated by Django 4.0 on 2022-08-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientmodel_tag_clientmodel_timezone_and_more'),
        ('message_sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_stamp', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientmodel')),
                ('message_sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_sender.messagesendermodel')),
            ],
        ),
    ]
