# Generated by Django 4.0 on 2022-08-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0002_messagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['-status']},
        ),
    ]
