# Generated by Django 4.0 on 2022-08-19 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Формат: 7XXXXXXXXXX', max_length=8, validators=[django.core.validators.RegexValidator('^[7]{1}?[0-9]{10}')])),
            ],
        ),
    ]
