# Generated by Django 4.0 on 2022-08-19 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='mobile_operator_code',
            field=models.CharField(default=1, help_text='Код мобильного оператора', max_length=9, validators=[django.core.validators.RegexValidator('[0-9]+', message='Введите корректный код')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='phone',
            field=models.CharField(help_text='Формат: 7XXXXXXXXXX', max_length=11, validators=[django.core.validators.RegexValidator('^[7]{1}?[0-9]{10}', message='Введите корректный номер')]),
        ),
    ]
